enableStrictSsl: false

nodeLinker: node-modules

npmAlwaysAuth: false

npmAuditRegistry: "https://npm.pkg.github.com"

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
